# Uncomment the next line to define a global platform for your project
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks

platform :ios, '9.0'
use_frameworks!

target 'DYZB' do

  pod 'Alamofire'       #网络数据请求
  pod 'Kingfisher'      #网络图片加载
  pod 'MJUtility'

end
